
version: 2.1

orbs:
  heroku: circleci/heroku@1.2.2

jobs:
  build-and-test:
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pip install -r requirements.txt

         
workflows:
  main:
    jobs:
      - build-and-test
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build-and-test




